### ISSUE TITLE
Consistent use of spaces/tabs for indentation

### ISSUE THREAD

**Issue by christophgysin** [e2tools/e2tools#16]
We currently have a few files that mix both tabs and spaces.

We should be consistent through the whole code base, and maybe introduce something like [EditorConfig](https://editorconfig.org).

**Comment by ndim** [comment]
So far, I have tried to keep to the style of the files I have been changing regarding brace placement, tabs versus spaces, indentation depths, etc.

I would have done the following post e2tools-0.1:

  * Determine which coding style to use and define it well. (With ext2 being closely related to the Linux kernel, this might be the Linux kernel coding style.)

  * Format the code according to the coding style.

  * Provide proper configuration for common editors like emacs and vim.
    EditorConfig fits in there as well.

As this is not user visible, I would put this post e2tools-0.1 release.

**Comment by christophgysin** [comment]
We seem to have introduced a bunch of tabs in files that used spaces for indentation:
- README.md
- compiler-definitions.h
- e2tool-e2cp.c
- e2tool-e2tail.c
- e2tools.c
- tests/simple-test.shin

I can clean these up, I see no point delaying that to rush out a release.

We can delay introducing EditorConfig to later point.
