### ISSUE TITLE
Would you became to the new upstream of the Debian package e2tools ?

### ISSUE THREAD

**Issue by atzlinux** [e2tools/e2tools#23]
Hi,
    I'm the maintainer of the Debian package e2tools   --  https://packages.debian.org/source/testing/e2tools

Would you became to the new upstream of the e2tools package?

If you would, I'll update the Debian package.

Thanks!

xiao sheng wen

**Comment by christophgysin** [comment]
I'd be happy to offer this as the place to collaborate on e2tools. That said, I haven't been using e2tools myself in a while, and there aren't any other active maintainers. Would you like to help contributing?

**Comment by ndim** [comment]
I am the maintainer of the Fedora package for e2tools. I started maintaining https://github.com/ndim/e2tools/ in 2007 with patches not specific to Fedora which were better suited for upstream, but upstream had already disappeared back then. Christoph Gysin has done some independent work on e2tools circa 2015 (IIRC also in the context of Debian). In 2019, Christoph suggested a joint effort in https://github.com/e2tools/e2tools/, and so we did that.

As far as I know, this is the most recently updated and maintained version of e2tools you can find, so using this as upstream for distro packages makes sense to me. That is why the Fedora package which I maintain uses this as upstream.

Of course, contributions are always welcome, and there are a few open things to be done (e.g. in the area of SELinux support). 

But just using this version of e2tools as it is for distro packages is also a good idea IMHO. Definitively better than using Keith Sheffield's original `e2tools-0.0.16`.

**Comment by atzlinux** [comment]
Good News! The new version deb package had changed the new upstream to this git repo.

https://tracker.debian.org/news/1211616/accepted-e2tools-010-1-source-into-unstable/

Thanks for you all!

**Comment by ndim** [comment]
Awesome!

I guess this concludes this github issue, so I am closing it. You are of course welcome to reopen or file a new issue when necessary.
