### ISSUE TITLE
Add SELinux label support

### ISSUE THREAD

**Issue by ndim** [e2tools/e2tools#4]
As of right now, e2tools lacks any support for SELinux. It neither displays SELinux labels in `e2ls`, nor does it have a `e2chcon` utility.

@crmulliner has submitted two pull requests to https://github.com/ndim/e2tools in the past which still need integration, preferrably with option and syntax as close to GNU coreutils `ls` as possible: https://github.com/ndim/e2tools/pull/2 and https://github.com/ndim/e2tools/pull/1

**Comment by crmulliner** [comment]
that would be nice, my fork of e2tools is just for the selinux integration, would be nice if this ends up here

**Comment by ndim** [comment]
Apparently, older versions of `libext2fs` (and some Ubuntu versions on travis-ci come with that older version) do not have xattr support (i.e. the `ext2fs_xattrs_*` functions), so I have just made building the SELinux support conditional on those functions actually being present.

We are still lacking these for more complete SELinux support, though, judging from reading the man pages for `chcon`, `cp`, `mkdir`, and `mv` looking for anything referring to SELinux:

   * new `e2chcon` utility
   * `e2cp` arguments `--context=` and `-Z`
   * `e2mkdir` arguments `--context=` and `-Z`
   * `e2mv` arguments `--context=` and `-Z`

**Comment by ndim** [comment]
@crmulliner The e2ls part of SELinux support has been merged and will be in `e2tools-0.1` in a few days. The rest of the SELinux support will then probably remain missing for some time to come.

**Comment by ndim** [comment]
AFAICT, this should be done. If you disagree, please reopen.
